Migration + Model
AT-PHPIntership/booking-hotel pull request #5
Opened 2018-07-24 08:37 UTC by at-tringuyen3

## Description
Database## Reference Requirements
- Task ID: TI-2

## Reference Isuees
#

## Migrations
YES

## SQL query and `explain`
NO

2018-07-25 04:01 UTC, ghost requested changes
check my comment! tks you

2018-07-25 04:01 UTC, at-tuannguyen3 commented on app/Model/Card.php
> +    protected $fillable = ['id', 'user_id', 'card_type', 'card_code'];
bỏ id đi vì id là increments rồi

2018-07-25 04:01 UTC, at-tuannguyen3 commented on app/Model/City.php
> +    protected $fillable = ['id', 'city', 'country'];
như trên bỏ id đi

2018-07-25 04:01 UTC, at-tuannguyen3 commented on app/Model/Comment.php
> +    public $timestamps = false;
không dùng timestamps ak

2018-07-25 04:01 UTC, at-tuannguyen3 commented on app/Model/Hotel.php
> +    protected $fillable = ['id', 'city_id', 'name', 'address', 'number_star', 'status', 'descript', 'user_id'];
như trên bỏ id đi

2018-07-25 04:01 UTC, at-tuannguyen3 commented on app/Model/Card.php
> +        return $this->belongsTo('App\User', 'user_id', 'id');
mình nghĩ nên tạo folder App\Models\ rồi bỏ model vào trong đó cho dễ quản lý chứ nhiều quá bỏ ở ngoài nó khó quản lý

2018-07-25 04:01 UTC, at-tuannguyen3 commented on app/Model/HotelImage.php
> +    public $timestamps = false;
thấy migration có dùng timestamps mà trong này ko dùng đến ak

2018-07-25 04:01 UTC, at-tuannguyen3 commented on app/Model/HotelImage.php
> +    protected $fillable = ['id', 'hotel_id', 'image'];
như trên bỏ luôn id đi nhé

2018-07-25 04:01 UTC, at-tuannguyen3 commented on database/migrations/2018_07_23_090020_create_places_table.php
> +            $table->foreign('city_id')->references('id')->on('cities')
thiếu column city_id để foreign thêm vào  $table->integer('city_id')->unsigned();

2018-07-25 09:34 UTC, ghost requested changes
check my comment! tks you

2018-07-25 09:34 UTC, at-tuannguyen3 commented on app/Model/Room.php
> +    public function roomType()
roomType đổi thành roomTypes

2018-07-25 09:34 UTC, at-tuannguyen3 commented on app/Model/User.php
> +    public function card()
đổi lại là cards

2018-07-25 09:34 UTC, at-tuannguyen3 commented on database/migrations/2018_07_23_090020_create_places_table.php
> +            $table->integer('user_id')->unsigned();
user_id ko tạo foreign ak

2018-07-25 09:34 UTC, at-tuannguyen3 commented on database/migrations/2018_07_23_090030_create_room_types_table.php
> +            $table->integer('hotel_id')->unsigned();
không có foreign cho user và hotel ạk

2018-07-25 09:34 UTC, at-tuannguyen3 commented on database/migrations/2018_07_23_090040_create_services_table.php
> +            $table->integer('status');
dùng kiểu boolean là đc rồi không thì dùng enum cũng đc

2018-07-25 09:34 UTC, at-tuannguyen3 commented on database/migrations/2018_07_23_090050_create_users_table.php
> +            $table->string('email');
thêm unique() cho email nữa nhé

2018-07-25 09:34 UTC, at-tuannguyen3 commented on database/migrations/2018_07_23_090050_create_users_table.php
> +            $table->string('username');
thêm unique() cho user name nữa

2018-07-25 09:34 UTC, at-tuannguyen3 commented on database/migrations/2018_07_23_090050_create_users_table.php
> +            $table->integer('role')->unsigned();
role có phải foreign vs bảng cards không, thêm foreign key cho nó luôn

2018-07-25 09:34 UTC, at-tuannguyen3 commented on database/migrations/2018_07_23_090050_create_users_table.php
> +            $table->string('phone');
string("phone", 20) là đủ rồi ak

2018-07-25 09:34 UTC, at-tuannguyen3 commented on database/migrations/2018_07_23_090060_create_cards_table.php
> +            $table->integer('user_id')->unsigned();
không có foreign key cho user ak

2018-07-25 09:34 UTC, at-tuannguyen3 commented on database/migrations/2018_07_23_090070_create_hotels_table.php
> +            $table->string('name');
thêm unique cho trường name nữa

2018-07-25 09:34 UTC, at-tuannguyen3 commented on database/migrations/2018_07_23_090070_create_hotels_table.php
> +            $table->integer('number_star')->unsigned();
number_star tại sao lại dùng unsigned nhỉ

2018-07-25 09:34 UTC, at-tuannguyen3 commented on database/migrations/2018_07_23_090070_create_hotels_table.php
> +            $table->integer('status');
dùng kiểu bolean là đc rồi ak

2018-07-25 09:34 UTC, at-tuannguyen3 commented on database/migrations/2018_07_23_090080_create_comments_table.php
> +            $table->integer('user_id')->unsigned();
move $table->integer('user_id')->unsigned(); xuống trước chổ foreign('user_id') để dễ nhìn hơn

2018-07-25 09:34 UTC, at-tuannguyen3 commented on database/migrations/2018_07_23_090080_create_comments_table.php
> +            $table->timestamps();
move $table->timestamps(); xuống dưới cùng luôn nhé

2018-07-25 09:34 UTC, at-tuannguyen3 commented on database/migrations/2018_07_23_090090_create_rooms_table.php
> +            $table->integer('price');
price dùng kiểu int ak đổi lại thành kiểu $table->double('price', 8, 2); nhé

2018-07-25 09:34 UTC, at-tuannguyen3 commented on database/migrations/2018_07_23_090090_create_rooms_table.php
> +            $table->integer('status');
kiểu bolean là đủ rồi á

2018-07-25 09:34 UTC, at-tuannguyen3 commented on database/migrations/2018_07_23_090090_create_rooms_table.php
> +            $table->timestamps();
move $table->timestamps(); xuống dưới cùng nha

2018-07-25 09:34 UTC, at-tuannguyen3 commented on database/migrations/2018_07_23_090110_create_room_bookeds_table.php
> +            $table->string('status');
status đổi thành kiểu boolean nhé

2018-07-25 09:34 UTC, at-tuannguyen3 commented on database/migrations/2018_07_23_090100_create_service_types_table.php
> +            $table->string('name');
thêm unique cho column name luôn

2018-07-26 02:08 UTC, at-tringuyen3 commented on database/migrations/2018_07_23_090070_create_hotels_table.php
> +            $table->integer('number_star')->unsigned();
cái ni kiểu như số sao của khách sạn á a. Nên phải cần lấy dương  á a

2018-07-26 02:09 UTC, at-tringuyen3 commented on database/migrations/2018_07_23_090050_create_users_table.php
> +            $table->integer('role')->unsigned();
Không phải a. Cái role ni mục đích là để phân quyền thôi a.

2018-07-26 02:47 UTC, at-tringuyen3 commented on database/migrations/2018_07_23_090070_create_hotels_table.php
> +            $table->string('name');
chỗ này cái name có thể trùng chớ a hè?

2018-07-26 03:20 UTC, ghost requested changes
check comment!

2018-07-26 03:20 UTC, at-tuannguyen3 commented on app/Model/Card.php
> +    public function users()
users bỏ s đi vì nó là số ít

2018-07-26 04:51 UTC, ghost requested changes
check my comment! tks you

2018-07-26 04:51 UTC, at-tuannguyen3 commented on app/Model/Hotel.php
> +        return $this->belongsToMany('App\Model\Service');
$this->belongsToMany('App\Model\Service', 'hotel_service', 'hotel_id', 'service_id'); làm vậy cho nó đảm bảo, còn làm kiểu $this->belongsToMany('App\Model\Service', 'hotel_service') thì Eloquent sẽ join 2 model tên liên quan theo thứ tự alphabetical.

2018-07-26 04:51 UTC, at-tuannguyen3 commented on app/Model/HotelService.php
> +    protected $table = 'hotelServices';
đổi tên bảng lại là hotel_services

2018-07-26 04:51 UTC, at-tuannguyen3 commented on app/Model/Service.php
> +        return $this->belongsToMany('App\Model\Hotel');
$this->belongsToMany('App\Model\Hotel', 'hotel_service', 'service_id', 'hotel_id');

2018-07-26 04:51 UTC, at-tuannguyen3 commented on app/Model/ServiceType.php
> +    public function hotels()
remove Relationship hotels đi nó không có quan hệ vs bảng ServiceType

2018-07-26 04:51 UTC, at-tuannguyen3 commented on app/Model/User.php
> +        return $this->belongsTo('App\Model\Comment', 'id', 'user_id');
sửa lại return $this->belongsTo('App\Model\Comment', 'user_id'); nếu dùng là $this->belongsTo('App\Model\Comment', 'user_id, 'local_key'); khi bảng mình có column khoá chính không phải là id (vd : id_abc) thì mình có thể để id_abc vào local_key để nó có thể join đc

2018-07-26 04:51 UTC, at-tuannguyen3 commented on database/migrations/2018_07_23_090050_create_users_table.php
> +            $table->integer('role')->unsigned();
$table->enum('role', ["admin", "supper_admin"]) hoặc có thể dùng kiểu boolean

2018-07-26 04:51 UTC, at-tuannguyen3 commented on database/migrations/2018_07_23_090060_create_cards_table.php
> +            $table->int('card_code')->unsigned();
tại sao lại dùng unsigned cho card_code nhỉ

2018-07-26 04:51 UTC, at-tuannguyen3 commented on database/migrations/2018_07_23_090070_create_hotels_table.php
> +            $table->string('name');
unique cho name hotel luôn

2018-07-26 04:51 UTC, at-tuannguyen3 commented on database/migrations/2018_07_23_090070_create_hotels_table.php
> +            $table->integer('number_star')->unsigned();
tại sao lại dùng unsigned() ở đây nhỉ?

2018-07-26 05:01 UTC, at-tuannguyen3 commented on database/migrations/2018_07_23_090060_create_cards_table.php
> +            $table->int('card_code')->unsigned();
$table->integer('card_code')->unsigned();

2018-07-26 07:23 UTC, ghost requested changes
check my comment again

2018-07-26 07:23 UTC, at-tuannguyen3 commented on database/migrations/2018_07_23_090050_create_users_table.php
> +            $table->enum('role', ["admin", "supper_admin"]);
chổ này anh vd thôi mà, còn tụi em làm có những quyền nào thì bỏ vô đó

2018-07-26 11:03 UTC, ghost approved these changes
LGTM

2018-07-26 11:03 UTC, merged